---
title: "Virospore annulus multi-quant for Magalie"
author: "Joy O'Brien"
date: "2025-03-22"
output: html_document
---

```{r setup, include=FALSE}
setwd("~/GitHub/VirosporeQuant/Magalie_virospore_quant")
```

```{r}
# Load Library
library(readxl)
library(dplyr)
library(tidyr)  
library(vegan)
library(ggplot2)
library(mgcv)

# Read in data
viro_quant <- read_excel("~/GitHub/VirosporeQuant/Magalie_virospore_quant/Data/Annulus_Quant/20250317_virospore_multiquant_magalie.xlsx", sheet = "raw_data")
```
1. Normalize the VPFU data to the area of pipette tip in cm 
```{r}
# Normalize the data to the area of the pipette tip (in cm) before calculating summary statistics (VPFU)
viro_quant$VPFU <- viro_quant$VPFU / 0.00785
```

2. Back calculate the free phage and uninfected spores from the dilutions and normalize to tip area (Come back to this and figure out why the total spores isn't working)
```{r}
# order of op-- 
# multiply counts by dilution factor and then divide by the area of the pipette tip
# create a new column with this data and call this column 
# Free phage
viro_quant$Free_PFU_3rep <- (viro_quant$Free_PFU_10e3 * 10^3) / 0.00785
viro_quant$Free_PFU_5rep <- (viro_quant$Free_PFU_10e5 * 10^5) / 0.00785
viro_quant$Free_PFU_7rep <- (viro_quant$Free_PFU_10e7 * 10^7) / 0.00785

# Uninfected spores
viro_quant$Spores_CFU_3rep <- (viro_quant$Spores_CFU_10e3 * 10^3) / 0.00785
viro_quant$Spores_CFU_5rep <- (viro_quant$Spores_CFU_10e5 * 10^5) / 0.00785
viro_quant$Spores_CFU_7rep <- (viro_quant$Spores_CFU_10e7 * 10^7) / 0.00785

# Total spores
#viro_quant$total_spores_3rep <-(viro_quant$VPFU + viro_quant$Spores_CFU_10e3)
#viro_quant$total_spores_5rep <- (viro_quant$VPFU + viro_quant$Spores_CFU_10e5)
#viro_quant$total_spores_7rep <- (viro_quant$VPFU + viro_quant$Spores_CFU_10e7)

```

```{r}
# New data frame
viro_quant.new <- viro_quant[, c("Plaque", "Sample", "Region", "VPFU", "Distance_from_PFU_center_cm", "Free_PFU_3rep","Free_PFU_5rep", "Free_PFU_7rep", "Spores_CFU_3rep", "Spores_CFU_5rep", "Spores_CFU_7rep")] #"total_spores_3rep", #"total_spores_5rep", #"total_spores_7rep

# Average the diluted replicate samples
viro_quant.new$Free_PFU_Avg <- rowMeans(viro_quant.new[, c("Free_PFU_3rep", "Free_PFU_5rep", "Free_PFU_7rep")], na.rm = TRUE)
viro_quant.new$Spores_CFU_Avg <- rowMeans(viro_quant.new[, c("Spores_CFU_3rep", "Spores_CFU_5rep", "Spores_CFU_7rep")], na.rm = TRUE)

# Average the total spores count 
#viro_quant.new$total_spores_Avg <- rowMeans(viro_quant.new[, c("total_spores_3rep", "total_spores_5rep", "total_spores_7rep")], na.rm = TRUE)
```

Plot all of the data with the averages used for CFU and PFU
```{r}
# Convert data to long format
viro_quant.long <- viro_quant.new %>%
  pivot_longer(cols = c(VPFU, Free_PFU_Avg, Spores_CFU_Avg), 
               names_to = "variable", 
               values_to = "value") #%>%
  #mutate(value = log(value))
# Log transform the data

viro_quant.long.all <- viro_quant.new %>%
  pivot_longer(cols = c(VPFU, Free_PFU_3rep, Free_PFU_5rep, Free_PFU_7rep, Free_PFU_Avg, Spores_CFU_3rep, Spores_CFU_5rep, Spores_CFU_7rep, Spores_CFU_Avg),
   names_to = "variable", 
               values_to = "value")

```

Plot all samples (individual dilutions)
```{r}
# Let's just plot of all of the reps to see what it looks like 
# Work on adding the regions for shading
region_shading <- data.frame(
  Region = c("Center", "Annulus", "Lawn"),
  xmin = c(0, 0.1, 0.2),   # Starting x-value for each region
  xmax = c(0.1, 0.2, 0.4)  # Ending x-value for each region
)
region_shading$Region <- factor(region_shading$Region, levels = c("Center", "Annulus", "Lawn"))


# Plot
ggplot(viro_quant.long.all, aes(x = Distance_from_PFU_center_cm, y = value, color = variable, group = variable)) +
  # Add shaded regions using geom_rect()
  geom_rect(data = region_shading, inherit.aes = FALSE, 
            aes(xmin = xmin, xmax = xmax, ymin = 0, ymax = Inf, fill = Region), 
            alpha = 0.3) +
  # Line and point layers
  geom_line(linewidth = 1.2) +  
  geom_point(aes(color = variable), size = 2) + 
  # Custom fill colors for shaded regions
  scale_fill_manual(values = c("Center" = "lightblue", "Annulus" = "lightgreen", "Lawn" = "lightpink")) +  

  # Log transformation for y-axis
  scale_y_log10() +
  # Labels 
  labs(title = "Virospore Multi-Quant Plot Plaque A", 
       x = "Distance from PFU center (cm)", 
       y = "Virospores, Free Phage, Uninfected Spores per cm^2", 
       color = "Measurement") +
  theme_minimal()
```

Plot Average PFU and CFU and virospores
```{r}
# Work on adding the regions for shading
region_shading <- data.frame(
  Region = c("Center", "Annulus", "Lawn"),
  xmin = c(0, 0.1, 0.2),   # Starting x-value for each region
  xmax = c(0.1, 0.2, 0.4)  # Ending x-value for each region
)
region_shading$Region <- factor(region_shading$Region, levels = c("Center", "Annulus", "Lawn"))

# Plot
ggplot(viro_quant.long, aes(x = Distance_from_PFU_center_cm, y = value, color = variable, group = variable)) +
  # Add shaded regions using geom_rect()
  geom_rect(data = region_shading, inherit.aes = FALSE, 
            aes(xmin = xmin, xmax = xmax, ymin = 0, ymax = Inf, fill = Region), 
            alpha = 0.3) +
  # Line and point layers
  geom_line(linewidth = 1.2) +  
  geom_point(aes(color = variable), size = 2) + 
  # Custom fill colors for shaded regions
  scale_fill_manual(values = c("Center" = "lightblue", "Annulus" = "lightgreen", "Lawn" = "lightpink")) +  
  # Log transformation for y-axis
  scale_y_log10() +
  # Labels 
  labs(title = "Virospore Multi-Quant Plot Plaque A", 
       x = "Distance from PFU center (cm)", 
       y = "Virospores, Free Phage, Uninfected Spores per cm^2", 
       color = "Measurement") +
  theme_minimal()


  # Custom colors for line and point data
  #scale_color_manual(values = c("coral", "cyan", "purple", "black"), 
                     #labels = c("Uninfected spores", "Free phage", "Virospores", "Total spores")) + 
```
  

